[package]
name = "deranger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winter = { version = "0.1.0", path = "../winter" }
winwalk = { version = "0.2.1", path = "../winwalk" }
